CREATE TABLE IF NOT EXISTS mobil (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  plat TEXT NOT NULL UNIQUE,
  sopir TEXT NOT NULL,
  kapasitas INTEGER NOT NULL CHECK (kapasitas > 0)
);

CREATE TABLE IF NOT EXISTS rute (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mobil_id INTEGER NOT NULL REFERENCES mobil(id),
  nama TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS titik (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  rute_id INTEGER NOT NULL REFERENCES rute(id),
  urutan INTEGER NOT NULL,
  nama TEXT NOT NULL,
  jam TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS siswa (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nama TEXT NOT NULL,
  kelas TEXT NOT NULL,
  titik_id INTEGER NOT NULL REFERENCES titik(id),
  ortu_nama TEXT,
  ortu_telepon TEXT
);

CREATE TABLE IF NOT EXISTS absen (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  siswa_id INTEGER NOT NULL REFERENCES siswa(id),
  tanggal TEXT NOT NULL,
  jam_naik TEXT,
  jam_turun TEXT,
  mobil_id INTEGER REFERENCES mobil(id),
  UNIQUE (siswa_id, tanggal)
);

CREATE TABLE IF NOT EXISTS posisi (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mobil_id INTEGER NOT NULL REFERENCES mobil(id),
  lat REAL NOT NULL,
  lng REAL NOT NULL,
  waktu TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS notifikasi (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  siswa_id INTEGER NOT NULL REFERENCES siswa(id),
  tanggal TEXT NOT NULL,
  waktu TEXT NOT NULL,
  jenis TEXT NOT NULL CHECK (jenis IN ('dijemput','tiba')),
  pesan TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_titik_rute ON titik(rute_id, urutan);
CREATE INDEX IF NOT EXISTS idx_absen_tgl ON absen(tanggal);
CREATE INDEX IF NOT EXISTS idx_posisi_mobil ON posisi(mobil_id, waktu);
